[package]
name = "gateway"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
application = { path = "../../crates/application" }
axum.workspace = true
common = { path = "../../crates/common" }
domain = { path = "../../crates/domain" }
mime_guess.workspace = true
observability = { path = "../../crates/observability" }
settings = { path = "../../crates/settings" }
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true
